server:
  port: 8086
#feign:
#  okhttp:
#    enabled: true
hm:
  db:
    host: 192.168.88.130
    database: hm-trade
    pw: 123
  swagger:
    title: "黑马商城交易服务接口文档"
    package: com.hmall.trade.controller