server:
  port: 8082
feign:
  okhttp:
    enabled: true

hm:
  db:
    host: 192.168.88.130
    database: hm-cart
    pw: 123
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: com.hmall.cart.controller

