# 应用服务 WEB 访问端口
server:
  port: 9091
  servlet:
    context-path: /api
# 错误页处理
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 547118
    driver-class-name: com.mysql.cj.jdbc.Driver
# 项目目录
project:
  folder: E:/E/ProjectFile/springboot/employee
# 日志级别配置
log:
  root:
    level: debug
