server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 547118
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: PT60M


# 配置MyBatis的XML映射文件的位置配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml