server:
  port: 8084
#feign:
#  okhttp:
#    enabled: true
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
  db:
    host: 192.168.88.130
    database: hm-user
    pw: 123
  swagger:
    title: "黑马商城用户服务接口文档"
    package: com.hmall.user.controller