server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_info
    username: root
    password: 547118
    driver-class-name: com.mysql.cj.jdbc.Driver
    # hikari连接池
    hikari:
      minimum-idle: 5  # 是连接池的一个属性，用于设置连接池中保持的最小空闲连接数
      idle-timeout: 180000  # 连接在连接池中空闲的最长时间（以毫秒为单位）后被回收的时间
      maximum-pool-size: 10  # 这是连接池中允许的最大连接数
      auto-commit: true  # 连接是否自动提交事务
      pool-name: easyjavaPool  # 连接池的名称，可以用来标识不同的连接池
      max-lifetime: 1800000  # 连接在连接池中最长的生命周期（以毫秒为单位）1800s
      connection-timeout: 30000  # 尝试获取连接的最长等待时间
      connection-test-query: SELECT 1  # 用于测试连接的SQL查询