server:
  port: 8081
#feign:
#  okhttp:
#    enabled: true

hm:
  db:
    host: 192.168.88.130
    database: hm-item
    pw: 123
  swagger:
    title: "黑马商城商品服务接口文档"
    package: com.hmall.item.controller