server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
        server-addr: 192.168.88.130:8848
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**